#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0; FAIL=0
check() { local n=$1; shift; if "$@"; then echo "PASS: $n"; PASS=$((PASS+1)); else echo "FAIL: $n"; FAIL=$((FAIL+1)); fi; }
echo "== bunker =="
check "zones.json" test -f "$ROOT/config/zones.json"
check "bunker-tui full CRUD" grep -qE 'Mode::Add|cycle_color|rename_zone|delete_zone' "$ROOT/tools/bunker-tui/src/main.rs"
check "bunker-tui nym/i2p/tor" grep -q 'nym.*i2p.*tor' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui nym-tor cascade" grep -q 'nym-tor' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui i2p-tor cascade" grep -q 'i2p-tor' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui tor-nym cascade" grep -q 'tor-nym' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui i2p-nym cascade" grep -q 'i2p-nym' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui term enter" grep -q 'fn run_term' "$ROOT/tools/bunker-tui/src/main.rs"
check "guest cascade offsets" grep -q 'i2p-nym' "$ROOT/modules/guests/mk-app-zone.nix"
check "netVM tor-cascade-i2p" grep -q 'tor-cascade-i2p' "$ROOT/modules/guests/net.nix"
check "netVM nym-via-i2p" grep -q 'nym-via-i2p' "$ROOT/modules/guests/net.nix"
check "host slots in bunkerAppZones" grep -q 'allBuildZones' "$ROOT/flake.nix"
check "bridge attaches vm-d" grep -q 'vm-\*' "$ROOT/modules/microvm-network.nix"
check "sflc link_all_unlocked" grep -q 'link_all_unlocked' "$ROOT/scripts/bunker-sflc.sh"
check "mutable zones path" grep -q '/var/lib/bunker/zones.json' "$ROOT/scripts/lib-common.sh"
check "kleopatra kdePackages" grep -q 'kdePackages.kleopatra' "$ROOT/templates/personal.nix"
check "no ventoy-full default" bash -c "! grep -q ventoy-full \"$ROOT/templates/personal.nix\""
check "tui hidden net locked" grep -q 'net fixed by slot' "$ROOT/tools/bunker-tui/src/main.rs"
check "iso-run" test -f "$ROOT/scripts/iso-run.sh"
check "iso multi-arch" grep -q 'riscv64\|aarch64' "$ROOT/scripts/iso-run.sh"
check "flake multi-system" grep -q 'aarch64-linux' "$ROOT/flake.nix"
check "flake riscv64" grep -q 'riscv64-linux' "$ROOT/flake.nix"
check "hw aarch64" test -f "$ROOT/hardware/generic-aarch64.nix"
check "hw riscv64" test -f "$ROOT/hardware/generic-riscv64.nix"
check "iso-qemu module" test -f "$ROOT/modules/iso-qemu.nix"
check "net has nym" grep -q 'nym-client' "$ROOT/modules/guests/net.nix"
check "net has i2pd" grep -q 'i2pd' "$ROOT/modules/guests/net.nix"
check "net has tor" grep -q 'services.tor' "$ROOT/modules/guests/net.nix"
check "netVM ip_forward off" grep -q 'ip_forward.*= 0' "$ROOT/modules/guests/net.nix"
check "netVM no NAT add" bash -c "! grep -qE 'nat -A POSTROUTING.*MASQUERADE' \"$ROOT/modules/guests/net.nix\""
check "netVM FORWARD DROP" grep -q 'FORWARD DROP' "$ROOT/modules/guests/net.nix"
check "netVM Tor DNSPort" grep -q 'DNSPort' "$ROOT/modules/guests/net.nix"
check "guest no default GW" grep -q 'mkForce null' "$ROOT/modules/guests/mk-app-zone.nix"
check "guest SOCKS-only OUTPUT" grep -q 'tcp --dport' "$ROOT/modules/guests/mk-app-zone.nix"
check "no host mat2" bash -c "! grep -q mat2 \"$ROOT/modules/host-minimal.nix\""
check "browse metadata-cleaner" grep -q metadata-cleaner "$ROOT/templates/browser.nix"
check "work julia" grep -q julia "$ROOT/templates/dev.nix"
check "personal template" test -f "$ROOT/templates/personal.nix"
check "vault template" test -f "$ROOT/templates/vault.nix"
check "vault airgap" python3 -c "import json;z=json.load(open('$ROOT/config/zones.json'));assert z['vault']['internet']=='none'"
check "public zones no radio" python3 -c "import json;z=json.load(open('$ROOT/config/zones.json'));assert 'radio' not in z"
check "public zones no invisible" python3 -c "import json;z=json.load(open('$ROOT/config/zones.json'));assert not any(c.get('invisible') for c in z.values())"
check "slots.json d1" python3 -c "import json;s=json.load(open('$ROOT/config/slots.json'));assert 'd1' in s and s['d1']['template']=='radio'"
check "flake builds slots" grep -q 'deniableSlots' "$ROOT/flake.nix"
check "sflc hidden-zones merge" grep -q 'hidden-zones.json' "$ROOT/scripts/bunker-sflc.sh"
check "sflc write-hidden" grep -q 'write-hidden' "$ROOT/scripts/bunker-sflc.sh"
check "zone-start resolves slot" grep -q 'bunker_zone_runtime_id' "$ROOT/scripts/zone-start.sh"
check "tui deniable hide/slot" grep -qE 'is_hidden|load_slots|write-hidden' "$ROOT/tools/bunker-tui/src/main.rs"
check "zone terminal color" grep -q 'BUNKER_ZONE_COLOR\|color.ansi' "$ROOT/modules/guests/mk-app-zone.nix"
check "bunker-term OSC" grep -q 'BUNKER_ZONE_COLOR' "$ROOT/scripts/zone-term.sh"
check "host clearnet lock" test -f "$ROOT/modules/host-net-lock.nix"
check "host-net script" test -x "$ROOT/scripts/bunker-host-net.sh"
check "host imports lock" grep -q 'host-net-lock.nix' "$ROOT/hosts/bunker/configuration.nix"
check "panic" grep -q '"panic"' "$ROOT/config/zones.json"
check "sflc real mode" grep -q '"shufflecake"' "$ROOT/config/shufflecake.json"
check "sflc no stub fallback" bash -c "! grep -q 'stub dir' \"$ROOT/scripts/bunker-sflc.sh\""
check "sflc bootstrap" grep -q 'bootstrap' "$ROOT/scripts/bunker-sflc.sh"
check "file-copy script" test -f "$ROOT/scripts/file-copy.sh"
check "tui file+unlock" grep -qE 'FileCopy|UnlockPass|run_file_copy' "$ROOT/tools/bunker-tui/src/main.rs"
check "tui start/usb/host/boot" grep -qE 'Mode::Start|Mode::Usb|Mode::HostNet|Mode::BootstrapPass' "$ROOT/tools/bunker-tui/src/main.rs"
check "zone-start uses bunker_zones_json" grep -q 'bunker_zones_json' "$ROOT/scripts/zone-start.sh"
check "panic lock stops VMs" grep -q "panic')=='lock'" "$ROOT/scripts/bunker-panic.sh"
check "no dead colors.json export" bash -c "! grep -q 'colors.json' \"$ROOT/modules/zones-ui.nix\""
check "no duplicate bunker-file wrap in sflc" bash -c "! grep -q 'bunker-file' \"$ROOT/modules/shufflecake-deniable.nix\""
echo "== $PASS passed, $FAIL failed =="
[[ $FAIL -eq 0 ]]
