#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0; FAIL=0
check() { local n=$1; shift; if "$@"; then echo "PASS: $n"; PASS=$((PASS+1)); else echo "FAIL: $n"; FAIL=$((FAIL+1)); fi; }
echo "== bunker =="
check "zones.json" test -f "$ROOT/config/zones.json"
check "bunker-tui full CRUD" grep -qE 'Mode::Add|cycle_color|rename_zone|delete_zone' "$ROOT/tools/bunker-tui/src/main.rs"
check "bunker-tui nym/i2p/tor" grep -q 'nym.*i2p.*tor' "$ROOT/tools/bunker-tui/src/main.rs"
check "iso-run" test -f "$ROOT/scripts/iso-run.sh"
check "iso multi-arch" grep -q 'riscv64\|aarch64' "$ROOT/scripts/iso-run.sh"
check "flake multi-system" grep -q 'aarch64-linux' "$ROOT/flake.nix"
check "flake riscv64" grep -q 'riscv64-linux' "$ROOT/flake.nix"
check "hw aarch64" test -f "$ROOT/hardware/generic-aarch64.nix"
check "hw riscv64" test -f "$ROOT/hardware/generic-riscv64.nix"
check "iso-qemu module" test -f "$ROOT/modules/iso-qemu.nix"
check "net has nym" grep -q 'nym-client' "$ROOT/modules/guests/net.nix"
check "net has i2pd" grep -q 'i2pd' "$ROOT/modules/guests/net.nix"
check "net has tor" grep -q 'services.tor' "$ROOT/modules/guests/net.nix"
check "no host mat2" bash -c "! grep -q mat2 \"$ROOT/modules/host-minimal.nix\""
check "zone terminal color" grep -q 'BUNKER_ZONE_COLOR\|color.ansi' "$ROOT/modules/guests/mk-app-zone.nix"
check "bunker-term OSC" grep -q 'BUNKER_ZONE_COLOR' "$ROOT/scripts/zone-term.sh"
check "host clearnet lock" test -f "$ROOT/modules/host-net-lock.nix"
check "host-net script" test -x "$ROOT/scripts/bunker-host-net.sh"
check "host imports lock" grep -q 'host-net-lock.nix' "$ROOT/hosts/bunker/configuration.nix"
check "invisible" grep -q '"invisible"' "$ROOT/config/zones.json"
check "panic" grep -q '"panic"' "$ROOT/config/zones.json"
check "sflc real mode" grep -q '"shufflecake"' "$ROOT/config/shufflecake.json"
check "sflc no stub fallback" bash -c "! grep -q 'stub dir' \"$ROOT/scripts/bunker-sflc.sh\""
check "sflc bootstrap" grep -q 'bootstrap' "$ROOT/scripts/bunker-sflc.sh"
check "file-copy script" test -f "$ROOT/scripts/file-copy.sh"
check "tui file+unlock" grep -qE 'FileCopy|UnlockPass|run_file_copy' "$ROOT/tools/bunker-tui/src/main.rs"
echo "== $PASS passed, $FAIL failed =="
[[ $FAIL -eq 0 ]]
